### ISSUE TITLE
Task ID: 1.4.8 Fill in M1 Report ​​ 4.1 Software Estimation  ​4.2 Project Management

### ISSUE THREAD

**Issue by jc0527** [Igshanmd/ICT2101-2201-Train-Services-P2-3#39]
Task title ID: 1.4.8 Fill in M1 Report ​​ 4.1 Software Estimation ​4.2 Project Management
1. To define the project's purpose, objectives, scope, and stakeholders. Develop a detailed project plan that includes tasks, timelines, resource allocation, and budget estimates. Planning also involves identifying potential risks and creating strategies for risk mitigation.
2. Goal: To provide a visual representation of a project's timeline and add it into M1 report
3. Success will be team vetted through and approved
4. Allocated time : 4 days
5. Start date: 15/09/23 1300. End date: 19/09/23 1300
6. Owner : jc0527

**Comment by KhairinNor** [comment]
Describe work done in detail: 4.1 and 4.2 have been populated in M1 successfully
Work committed to branch: NIL
Does work affect deadline: Yes but it was mostly due to some changes that was needed to be made.
Success criteria or completion: The team has vetted and checked. Everything is complete.
Start date of work done: 15 Sept 2023
End date of work done: 19 Sept 2023
